import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
import { useSession, signIn, signOut } from "next-auth/react";
export default function Home() {
  const session = useSession();
  console.log("session", session);
  if (session.data === null) {
    return <button onClick={signIn}>login</button>;
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Link href={`/`}>
            <button>Home</button>
          </Link>
          <Link href={`/profile/tausif`}>
            <button>profile</button>
          </Link>
          <Link href={`/server/users`}>
            <button>server</button>
          </Link>
          <Link href={`/static/users`}>
            <button>static</button>
          </Link>
          <Link href={`/user/header`}>
            <button>user</button>
          </Link>
          <Link href={`/product`}>
            <button>product</button>
          </Link>
          <Link href={`/usersdata/index`}>
            <button>userdata</button>
          </Link>
          <Link href={`/`}>
            <button>empty</button>
          </Link>
          <button onClick={signOut}>signOut</button>
        </div>
        <div className={styles.grid}>
          <h5>{session?.data?.user?.name}</h5>
        </div>
      </main>
    </>
  );
}
